sudo: false
language: generic
env:
  global:
    - CURL="curl -fsSkL --retry 9 --retry-delay 9"
    - GHRAW="https://raw.githubusercontent.com"
    - BUILD_MAGIT_LIBGIT="false"
  matrix:
  - EMACS_VERSION=25.1
  - EMACS_VERSION=master
  allow_failures:
    - env: EMACS_VERSION=master

install:
  - $CURL -O https://downloads.kitenet.net/git-annex/linux/current/git-annex-standalone-amd64.tar.gz
  - tar -xaf git-annex-standalone-amd64.tar.gz
  - export PATH="$PWD/git-annex.linux${PATH:+:}$PATH"
  - export LOCPATH=
  - $CURL -O https://github.com/npostavs/emacs-travis/releases/download/bins/emacs-bin-${EMACS_VERSION}.tar.gz
  - tar -xaf emacs-bin-${EMACS_VERSION}.tar.gz -C /
  - export EMACS=/tmp/emacs/bin/emacs
  - git clone --quiet https://github.com/magit/magit.git
  - cd magit
  - $CURL -O ${GHRAW}/magnars/dash.el/master/dash.el
  - $CURL -O ${GHRAW}/magit/ghub/master/ghub.el
  - $CURL -O ${GHRAW}/magit/ghub/master/ghub-graphql.el
  - $CURL -O ${GHRAW}/vermiculus/graphql.el/master/graphql.el
  - $CURL -O ${GHRAW}/abo-abo/hydra/master/lv.el
  - $CURL -O ${GHRAW}/magit/transient/master/lisp/transient.el
  - $CURL -O ${GHRAW}/volrath/treepy.el/master/treepy.el
  - $CURL -O ${GHRAW}/magit/with-editor/master/with-editor.el
  - $EMACS -Q --batch -L . -f batch-byte-compile dash.el ghub.el ghub-graphql.el graphql.el transient.el treepy.el with-editor.el
  - make lisp EMACSBIN=$EMACS DASH_DIR=$PWD
  - cd ..
  - git annex version
  - $EMACS --batch -L magit -L magit/lisp --eval "(progn (require 'magit) (magit-version t))"

script:
  - git config --global user.name "A U Thor"
  - git config --global user.email a.u.thor@example.com
  - make EMACSBIN=$EMACS LOAD_PATH="-L magit -L magit/lisp"
  - make test EMACSBIN=$EMACS LOAD_PATH="-L magit -L magit/lisp"

notifications:
  email:
    on_success: never
    on_failure: always
